<?php

namespace Proyecto\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConceptosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosRepository extends EntityRepository
{
}
