<?php

namespace Proyecto\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadisticasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticasRepository extends EntityRepository
{
}
